import fs from 'node:fs';
import { applicationGuides, applicationGuideById, applicationProductNotes } from '../data/application-guides.mjs';
import { productById, productUrl, groupUrl, tr as t } from '../data/portfolio.mjs';
import { fixtureGroups, fixtureUrl } from '../data/fixtures.mjs';
import { applicationDiagram } from './application-diagrams.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const assets=new Map(JSON.parse(fs.readFileSync(new URL('../data/portfolio-assets.json',import.meta.url),'utf8')).map(a=>[a.id,a.local]));
const legacy=new Map(JSON.parse(fs.readFileSync(new URL('../product-inventory/application-review/sources.json',import.meta.url),'utf8')).map(s=>[s.id,s]));
const photo=p=>p.existingFamily?'/assets/products/'+p.existingFamily+'.png':assets.get(p.image?.id);
const href=(url,label)=>`<a href="${esc(url)}">${esc(label)}</a>`;
export const applicationImage=g=>photo(productById.get(g.productIds[0]));

export function applicationHub(lang){
  return `<section class="section-shell directory-hero"><p class="eyebrow">LABOMAK / ${t(lang,'APPLICATION GUIDES','UYGULAMA REHBERLERİ')}</p><h1>${t(lang,'What do you need to measure?','Neyi ölçmek istiyorsunuz?')}</h1><p>${t(lang,'Start with the test objective. Understand the method, explore the measurement choices, and find the machines and fixtures that fit your specimens.','Test amacıyla başlayın. Metodu öğrenin, ölçüm seçeneklerini inceleyin ve numunelerinize uygun cihazları ve fikstürleri bulun.')}</p></section><div class="section-shell application-hub-grid">${applicationGuides.map((g,i)=>`<a href="${groupUrl(lang,'applications',g.id)}"><span class="eyebrow">${String(i+1).padStart(2,'0')} / ${g.productIds.length} ${t(lang,'equipment options','ekipman seçeneği')}</span><h2>${esc(g.name[lang])}</h2><p>${esc(g.description[lang])}</p><b>${t(lang,'Read the guide','Rehberi okuyun')} →</b></a>`).join('')}</div>`;
}

export function applicationBody(g,lang,quote){
  const related=g.productIds.map(id=>productById.get(id));
  const url=groupUrl(lang,'applications',g.id);
  const schema={'@context':'https://schema.org','@type':'WebPage','@id':'https://labomak.com.tr'+url+'#guide',url:'https://labomak.com.tr'+url,name:g.name[lang],description:g.description[lang],inLanguage:lang,about:{'@type':'Thing',name:g.name[lang]},primaryImageOfPage:{'@type':'ImageObject',contentUrl:'https://labomak.com.tr'+applicationImage(g)},mainEntity:{'@type':'ItemList',name:t(lang,'Related testing equipment','İlgili test ekipmanları'),itemListElement:related.map((p,i)=>({'@type':'ListItem',position:i+1,name:p.name[lang],url:'https://labomak.com.tr'+productUrl(lang,p)}))}};
  const nav=[['overview',t(lang,'The method','Metot')],['results',t(lang,'Results','Sonuçlar')],['preparation',t(lang,'Test setup','Test düzeni')],['faq',t(lang,'FAQ','Sık sorulanlar')],['equipment',t(lang,'Equipment','Ekipman')],...(g.fixtureIds.length?[['application-fixtures',t(lang,'Fixtures','Fikstürler')]]:[]),['references',t(lang,'References','Kaynaklar')]];
  return `<script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script>
  <section class="section-shell application-hero"><div><p class="eyebrow">LABOMAK / ${t(lang,'APPLICATION GUIDE','UYGULAMA REHBERİ')}</p><h1>${esc(g.name[lang])}</h1><p>${esc(g.description[lang])}</p><div class="hero-actions"><a class="button button-filled" href="#equipment">${t(lang,'Find equipment','Ekipman bulun')} ↗</a><a class="text-link" href="#overview">${t(lang,'Understand the test','Testi tanıyın')} ↓</a></div></div>${applicationDiagram(g.id,lang)}</section>
  <nav class="section-shell application-toc" aria-label="${t(lang,'On this application page','Bu uygulama sayfasında')}">${nav.map(([id,label])=>href('#'+id,label)).join('')}</nav>
  <section class="section-shell application-explanation" id="overview"><div><p class="eyebrow">01 / ${t(lang,'UNDERSTAND THE METHOD','METODU TANIYIN')}</p><h2>${esc(g.name[lang])}: ${t(lang,'what does it measure?','ne ölçülür?')}</h2></div><div class="application-prose"><p>${esc(g.overview[lang])}</p><aside class="application-insight"><h3>${t(lang,'Interpret the result correctly.','Sonucu doğru yorumlayın.')}</h3><p>${esc(g.distinction[lang])}</p></aside></div></section>
  <section class="section-shell application-section" id="results"><p class="eyebrow">02 / ${t(lang,'READ THE RESULTS','SONUÇLARI OKUYUN')}</p><h2>${t(lang,'From measurement to a useful result.','Ölçümden anlamlı sonuca.')}</h2><div class="application-results">${g.results.map(r=>`<article><h3>${esc(r.title[lang])}</h3><p>${esc(r.body[lang])}</p></article>`).join('')}</div></section>
  <section class="section-shell application-section" id="preparation"><p class="eyebrow">03 / ${t(lang,'PLAN THE TEST','TESTİ PLANLAYIN')}</p><h2>${t(lang,'Define the conditions before testing.','Test öncesinde koşulları tanımlayın.')}</h2><ol class="application-variables">${g.variables.map((v,i)=>`<li><span aria-hidden="true">0${i+1}</span><div><h3>${esc(v.title[lang])}</h3><p>${esc(v.body[lang])}</p></div></li>`).join('')}</ol></section>
  <section class="section-shell application-explanation" id="faq"><div><p class="eyebrow">04 / ${t(lang,'PRACTICAL ANSWERS','PRATİK YANITLAR')}</p><h2>${t(lang,'Frequently asked questions','Sık sorulan sorular')}</h2><p class="application-faq-context">${esc(g.name[lang])}</p></div><div class="application-faq">${g.faq.map((f,i)=>`<details${i===0?' open':''} id="faq-${i+1}"><summary>${esc(f.question[lang])}</summary><p>${esc(f.answer[lang])}</p></details>`).join('')}</div></section>
  <section class="section-shell application-section" id="equipment"><p class="eyebrow">05 / ${t(lang,'MATCH THE EQUIPMENT','EKİPMANI SEÇİN')}</p><div class="section-title"><h2>${t(lang,'Build your test setup.','Test düzeneğinizi oluşturun.')}</h2><a class="text-link" href="#enquire">${t(lang,'Get selection support','Seçim desteği alın')} ↗</a></div><p class="application-section-intro">${t(lang,'Choose by the specimen, required measurement and test method. Confirm the load range, accessories and final configuration for your application.','Numuneye, gereken ölçüme ve test metoduna göre seçin. Yük aralığını, aksesuarları ve nihai konfigürasyonu uygulamanız için doğrulayın.')}</p><div class="application-equipment">${related.map(p=>`<article data-application-product="${p.id}"><a class="application-product-photo" href="${productUrl(lang,p)}"><img src="${photo(p)}" alt="${esc(p.name[lang])}" width="360" height="280" loading="lazy" decoding="async"></a><div><h3>${href(productUrl(lang,p),p.name[lang])}</h3><p>${esc(p.intro[lang])}</p>${applicationProductNotes[g.id]?.[p.id]?`<p class="application-product-note">${esc(applicationProductNotes[g.id][p.id][lang])}</p>`:''}<a class="text-link" href="${productUrl(lang,p)}">${t(lang,'View equipment','Ekipmanı inceleyin')} →</a></div></article>`).join('')}</div></section>
  ${g.fixtureIds.length?`<section class="section-shell application-section" id="application-fixtures"><p class="eyebrow">${t(lang,'THE SPECIMEN CONNECTION','NUMUNE BAĞLANTISI')}</p><h2>${t(lang,'Complete the setup with the right fixtures.','Düzeneği uygun fikstürlerle tamamlayın.')}</h2><div class="application-fixtures">${g.fixtureIds.map(id=>{const f=fixtureGroups.find(g=>g.id===id);return `<a href="${fixtureUrl(lang,id)}"><img src="${assets.get(f.examples[0].image.id)}" alt="${esc(f.name[lang])}" width="200" height="180" loading="lazy"><div><h3>${esc(f.name[lang])}</h3><span>${f.examples.length} ${t(lang,'illustrated examples','görselli örnek')} →</span></div></a>`;}).join('')}</div></section>`:''}
  <section class="section-shell application-explanation application-references" id="references"><div><p class="eyebrow">${t(lang,'METHOD REFERENCES','METOT KAYNAKLARI')}</p><h2>${t(lang,'Go to the source.','Kaynağı inceleyin.')}</h2><p>${t(lang,'Check the applicable edition and material scope before specifying a test. These references explain methods; equipment compatibility depends on its configuration.','Testi belirlemeden önce geçerli baskıyı ve malzeme kapsamını kontrol edin. Bu kaynaklar metotları açıklar; ekipman uyumluluğu konfigürasyona bağlıdır.')}</p></div><ul>${g.references.map(r=>`<li>${href(r.url,r.name+' ↗')}</li>`).join('')}${legacy.has(g.id)?`<li>${href(legacy.get(g.id).url,t(lang,'Original Labomak application page (Turkish)','Orijinal Labomak uygulama sayfası')+' ↗')}</li>`:''}</ul></section>
  ${quote(lang,{id:'application-'+g.id,name:g.name[lang]})}
  <section class="section-shell application-section"><h2>${t(lang,'Explore connected test methods.','İlgili test metotlarını keşfedin.')}</h2><div class="application-related">${g.related.map(id=>{const other=applicationGuideById.get(id);return href(groupUrl(lang,'applications',id),other.name[lang]+' →');}).join('')}</div></section>`;
}
